// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFLr6kkrBkorZCQ_XRfNAPoajTlxFOXR4',
    appId: '1:1008181776457:web:86e866fef0be0e1f0baf98',
    messagingSenderId: '1008181776457',
    projectId: 'shashlikuz-77716',
    authDomain: 'shashlikuz-77716.firebaseapp.com',
    storageBucket: 'shashlikuz-77716.appspot.com',
    measurementId: 'G-FBQGJBJZRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRmlWngGjniSD89UGscxjUmvpCMwZeXng',
    appId: '1:1008181776457:android:4786ffa67a41c7f40baf98',
    messagingSenderId: '1008181776457',
    projectId: 'shashlikuz-77716',
    storageBucket: 'shashlikuz-77716.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClFn9aNzeVAGzK8XXKds57DxfmNxgBkZs',
    appId: '1:1008181776457:ios:7ad1cb7b93f4edae0baf98',
    messagingSenderId: '1008181776457',
    projectId: 'shashlikuz-77716',
    storageBucket: 'shashlikuz-77716.appspot.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClFn9aNzeVAGzK8XXKds57DxfmNxgBkZs',
    appId: '1:1008181776457:ios:7ad1cb7b93f4edae0baf98',
    messagingSenderId: '1008181776457',
    projectId: 'shashlikuz-77716',
    storageBucket: 'shashlikuz-77716.appspot.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFLr6kkrBkorZCQ_XRfNAPoajTlxFOXR4',
    appId: '1:1008181776457:web:2d7453c7d9ba7d1e0baf98',
    messagingSenderId: '1008181776457',
    projectId: 'shashlikuz-77716',
    authDomain: 'shashlikuz-77716.firebaseapp.com',
    storageBucket: 'shashlikuz-77716.appspot.com',
    measurementId: 'G-6DE6VVH40S',
  );
}
